```{r init}
set.seed(12345)
#stop('Don\'t run me dummy')
#rm(list=ls()) # clear workspace
cat('\014') # clear console
knitr::opts_chunk$set(
  eval=T
  ,include=F
  ,paged.print=F
)
library(tilit);library(magrittr)
'data.table,disk.frame,ggplot2,igraph,network,intergraph,forcats,shiny,shinyjs,miniUI,shinyPagerUI,ggiraph,dendextend,ggdendro' %>% ec %>% sapply(library,character.only = T) %>% invisible # load packages
if(!dir.exists('d')) system('mkdir d && (cd d && mkdir q d p b)') # create data directory structure if it doesn't exist
setDTthreads(threads = 3) # binder limits combined cpu load to 1 core's worth, so core use should be discounted
#if(parallel::detectCores()>1&getDTthreads()==1) setDTthreads(threads=2)
nc<-getDTthreads() # for functions asking for number of cores
nchnk<-nc*2^4
{DF<-T;if(DF) {setup_disk.frame();options(future.globals.maxSize = Inf)}} # set up disk frame
cpumem<-function(download=T,browse=T,...) {
  if(F) {tilit::cpumem(...)
    if(download|browse) Sys.getenv('RSTUDIO_HTTP_REFERER') %>% {if(.!='') if(interactive()) {
      if(download) browseURL(sprintf('%sexport/cpumem.png?name=cpumem.png&file=~%%2Fcpumem.png',.))
      if(browse) browseURL(sprintf('%sfiles/cpumem.png',.))
    }}
  }
}
cpumem(F,F)
thr<-.1
```

# Import WOK Data

```{r wok2dbl}
f<-'d/p/wok2dbl.RData'
# create link to original location in clean data structure 
if(!file.exists(f)) system('link Out/wok2dbl.RData d/p/wok2dbl.RData')
if(file.exists(f)){
  load(f)
} else {
  # Code that would generate database, but load saved data instead. Note original WOK records absent from repository.
  wok2dbl<-plagiat::wok2dbl.f(dir = 'WoS.TextFiles.19Sept2018.61551/', out = 'Out')
  save(wok2dbl,file=f)
}
rm(f)
wok2dbl<-unique(wok2dbl)
if(DF) {wok2dfl<-as.disk.frame(wok2dbl);rm(wok2dbl)}
cpumem(plot=T)
```

# Cleaning

```{r dbl2crl}
f<-'d/q/dbl2crl.txt.gz'
if(file.exists(f)){
  warning(sprintf('%s already exists. Manually delete to replace.\nReturning dbl2cro cleaning key.\n',f))
  dbl2cro<-fread(sub('crl','cro',f))
} else {
  dbl2crl.f<-function(){
    crl<-data.table(cro={if(DF) srckeep(wok2dfl,ec('field,val')) else wok2dbl}['CR',on='field',val %>% unique])[,cr:=cro %>%  toupper %>% sub(', DOI.+','',.) %>% gsub('<[^>]+>','',.) %>% sub('^[ANONYMOUS]','',.,fixed=T)] %>% setcolorder(2:1) 
    # write original keyed to trimmed
    fwrite(x = crl[cr!=cro],file=sub('crl','cro',f),quote = F,sep = '\t')
    crl[,cro:=NULL]
    if(anyDuplicated(crl)) crl<-unique(crl)
    # write just levels
    fwrite(x = crl,file=f,quote = F,sep = '\t')
  }
  dbl2crl.f()
  dbl2cro<-fread(sub('crl','cro',f))
}
rm(f)
```

## Fuzzy set replacement

```{r crl2reg}
#CR levels to regionalized match candidates. Processor intensive, so performed on Google Cloud server.
f<-'d/qq/crl2reg.txt.gz'
if(file.exists(f)){
  load(sub('.txt.gz','.RData',f,fixed = T))
} else {
  crl2reg.f<-function(thr=.1){
    crl2reg<-try(fread(f))
    if(inherits(crl2reg,'try-error')) {minit<-list();ix<-0} else {
      ix<-try(dbl2crl[,which(cr==crl2reg[.N,cr])])
      if(inherits(ix,'try-error')) {minit<-list();ix<-0} else {minit<-crl2reg[,as.list(cr)]}
    }
    ix<-ix+1
    dbl2crl[,{
      m<-minit
      pbapply::pblapply(ix:.N,function(i) if(!cr[i]%in%m) {
        r<<-cr[-i][stringdist::amatch(x = cr[i],table = cr[-i],method = 'jw',maxDist = thr,nomatch = NA_character_)]
        if(!is.na(r)) {data.table(cr=cr[i],cra=r) %>% fwrite(f,append = T,quote=F,sep='\t');m[[length(m)+1]]<<-r}
      },cl = parallel::detectCores()/2)}]
    unique(fread(f))
  }
  crl2reg<-crl2reg.f()
  crl2reg %<>% .[,apply(.SD,1,sort) %>% t %>% data.table %>% setnames(ec('cr,cra'))] %>% unique
  save(crl2reg,file=sub('.txt.gz','.RData',f,fixed = T))
}

rm(f)
```

```{r reg2trn}
f<-'d/q/reg2trn.RData'
if(file.exists(f)){
  load(f)
} else {
  reg2trn.f<-function(thr=.1){
    g<-graph_from_edgelist(crl2reg %>% as.matrix,directed=F)
    trn<-data.table(cr=V(g)$name,cmp=components(g)$membership)[,cmp:=cmp %>% factor %>% fct_infreq %>% as.integer] %>% setkey(cmp,cr)
    trn
  }
  reg2trn<-reg2trn.f()
  save(reg2trn,file=f)
}
rm(f)
```

```{r trn2crm}
f<-'d/q/trn2crm.txt.gz'
if(file.exists(f)){
  load(sub('txt\\.gz','RData',f))
} else {
  # f %>% unlink
  trn2crm.f<-function(){
    trn<-reg2trn
    if(anyDuplicated(trn)) trn<-unique(trn)
    trn[,scr:=cr %>% strsplit(', ')][,l:=sapply(scr,length)] %>% setorder(-l)
    trn[,table(l) %>% plot]
    map<-function(y,dbg=F){
      if(dbg) cat(paste(y,collapse=', '))
      ix<-1:length(y)
      wY<-grep('^(([01][0-9]{3})|(20[012][0-9]))$',y[ix]) %>% {if(length(.)) ix[min(.)] else ''}
      ix<-setdiff(ix,wY)
      wV<-'^V[<0-9 ACXIDLVM]+$' %>% {ix[grep(.,y[ix])][1]} %>% {if(is.na(.)) '' else {if(wY>.) '' else .}}
      ix<-setdiff(ix,wV)
      wP<-'^P(\\[|[0-9 ACDFHILMNVX]+$)' %>% {rev(ix[grep(.,y[ix])])[1]} %>% {if(is.na(.)) '' else {if(wV>.) '' else .}}
      if(wV!=''&wP!='') wV<-wV:(wP-1)
      if(wP!='') wP<-ix[ix>=wP]
      ix<-setdiff(ix,wP)
      if(wY!='') {wA<-ix[ix<wY];wS<-ix[ix>wY]} else if(length(ix)>1) {wA<-ix[1];wS<-ix[2:length(ix)]} else {wA<-ix;wS<-ix}
      if(!length(wA)) wA<-''
      if(!length(wS)) wS<-''
      of<-function(z) z %>% {if(.[1]=='') . else paste(y[.],collapse=', ')}
      wD<-''
      of(wS) %>% {if(grepl('  +[0-9]{4}$',.)&wY!='') wD<<-sub('.+ ','',.);wS<<-sub('  .+','',.)}
      data.table(a=of(wA),y=of(wY),s=wS,d=wD,v=of(wV),p=of(wP))
    }
    pbapply::pblapply(1:length(trn$scr),function(x) data.table(trn[x,.(cr)],map(trn$scr[[x]]),ix=x) %>% fwrite(f,append = T,quote=F,sep='\t'),cl=parallel::detectCores()-1) %>% unlist
    crm<-fread(f,keepLeadingZeros=T)
    # year
    crm[,y:=as.integer(y)]
    # for p treat as list; v, d, as vector
    suppressWarnings(crm[,p:=as.list(p)][p!='',p:= pbapply::pblapply(p,function(x) x %>% strsplit(', ') %>% unlist %>% gsub('P|\\[|\\]','',.) %>% as.roman %>% as.integer,cl=3)])
    suppressWarnings(crm[,v:= pbapply::pbsapply(v,function(x) x %>% gsub('V|\\[|\\]','',.) %>% as.roman %>% as.integer,cl=3)])
    suppressWarnings(crm[,d:=as.list(d)][d!='',d:= paste0(y,d),by=ix][,d:=pbapply::pbsapply(d,function(x) x %>% lubridate::ymd(.) %>% as.numeric,cl=3)])
    crm[trn,on='cr',cmp:=cmp] %>% setkey(cmp)
    crm
  }
  trn2crm<-trn2crm.f()
  save(trn2crm,file=sub('txt\\.gz$','RData',f))
}
rm(f)
```

```{r crm2pwc, paged.print=FALSE}
f<-'d/q/crm2pwc.RData'
if(file.exists(f)){
  load(f)
} else {
  crm2pwc.f<-function(nhld=100,ntrn=500){
    # f %>% unlink
    # code categories
    kls<-data.table(expand.grid(Y=0:1,D=0:1,V=0:1,P=0:1))
    cls<-trn2crm[,.(cr,cmp,Y=is.na(y) %>% `!` %>% as.integer,D=is.na(d) %>% `!` %>% as.integer,V=is.na(v) %>% `!` %>% as.integer,P=(p!='') %>% as.integer)]
    cls<-ec('Y,D,V,P') %>% {n<-.;cls[kls,on=n][,cls:=.SD %>% apply(1,paste0,collapse=''),.SDcols=n]}
    cls<-cls[!is.na(cmp),]
    cls %>% setorder(cmp,cr)
    withr::with_package('pbapply',{
      grpn <- uniqueN(cls$cmp);int<-floor(grpn/100);pb <- timerProgressBar(min = 0, max = grpn,char='+',width=50)
      pwc<-cls[,.(crp={
        if(!.GRP%%int) setTimerProgressBar(pb,.GRP)
        utils::combn(cr,2,simplify=F)}),by=cmp]
      setTimerProgressBar(pb,grpn)
      closepb(pb)
      # progress bar https://github.com/Rdatatable/data.table/issues/1409
      n<-ec('Y,D,V,P')
      grpn <- nrow(pwc);pb <- timerProgressBar(min = 0, max = grpn,char='+',width=50)
      pwc[,(n):=NA_integer_][,ix:=.I][,u:=!ix%%100]
      setTimerProgressBar(pb,0)
      t<-Sys.time()
      pwc[,(n):={
        if(u) if(difftime(Sys.time(),t)>1) {setTimerProgressBar(pb,.GRP);t<<-Sys.time()}
        cls[.(unlist(crp)),.SD %>% apply(2,sum) %>% as.list,.SDcols=n]}
        ,by=ix] %>% setkey(Y,D,V,P)
      setTimerProgressBar(pb,grpn)
      closepb(pb)
    })
    pwc[,ec('ix,u'):=NULL]
    
    # partition
    pwc[,par:=.SD %>% sapply(function(x) as.integer(x==2)) %>% apply(1,paste0,collapse='') %>% factor %>% forcats::fct_infreq(.),.SDcols=ec('Y,D,V,P')]
    rnorm(1);seed<-.Random.seed[1]
    withr::with_seed(seed=seed,{
      pwc[,mls:=c(rep('trn',ntrn),rep('hld',nhld),rep('prd',(.N-(ntrn+nhld)) %>% {ifelse(.<0,0,.)}))[1:.N] %>% sample,by=par]
    })
    setattr(pwc,'seed',seed)
    pwc[,mls:=mls %>% factor %>% forcats::fct_infreq(.) %>% forcats::fct_rev(.)]
    setattr(pwc,'mlstab',pwc[,table(par,mls) %>% addmargins %>% {cbind(.,'1%'=ceiling(.01*.[,ncol(.)]))}])
    attr(pwc,'mlstab')
    pwc
  }
  crm2pwc<-crm2pwc.f()
  save(crm2pwc,file=f)
}
rm(f)
attr(crm2pwc,'mlstab')
```

```{r pwc2mlm}
f<-'d/q/pwc2mlm.RData'
if(file.exists(f)){
  load(f)
} else {
  pwc2mlm.f<-function(){
    
    # features anon nchar1/2 pa1/2 cr,a,s(jw/ds/lcs) dfy dfd dfv dfp 
    Y<-D<-V<-function(x){x %>% unlist %>% diff %>% abs}
    P<-function(x){do.call(outer,args=c(x,FUN='-')) %>% abs %>% min}
    setkey(trn2crm,cr)
    mmf<-function(var,dat=crm2pwc) trn2crm[dat$crp %>% unlist,get(var)] %>% matrix(ncol=2,byrow = T)
    
    # anon both strings anonymous
    crm2pwc[,anon:=sapply(crp,function(x) x %>% unlist %>% grepl('[ANONYMOUS]',.,fixed = T) %>% {if(sum(.)==2) 1 else 0})]
    
    # astr both strings asterisk
    crm2pwc[,anon:=sapply(crp,function(x) x %>% unlist %>% grepl('^\\*',.,fixed = T) %>% {if(sum(.)==2) 1 else 0})]
    
    # nchar1/2 raw string lengths
    crm2pwc[,ec('nchs,nchl'):=mmf('cr') %>% nchar %>% data.table]
    # pra1/2 proportion of alpha
    crm2pwc[,ec('pa1,pa2'):=mmf('cr') %>% apply(2,stringr::str_count,'[A-Za-z]') %>% data.table]
    crm2pwc[,pa1:=pa1/nchs][,pa2:=pa2/nchl]
    # order so shorter first and longer second
    {n<-ec('nchs,nchl,pa1,pa2');crm2pwc[,(n):=.SD %>% apply(1,function(x) order(x[1:2]) %>% {x[c(.,.+2)]}) %>% t %>% data.table,.SDcols=n]}
    
    # cr,a,s(jw/ds/lcs) string distances
    for(vr in ec('cr,a,s')) {
      crm2pwc[,paste0(vr,'jw'):=mmf(..vr) %>% {stringdist::stringdist(a=.[,1],b=.[,2],method='jw',p=.1)}] 
      crm2pwc[,paste0(vr,'sd'):=mmf(..vr) %>% {stringdist::stringdist(a=.[,1],b=.[,2])}] 
      crm2pwc[,paste0(vr,'lc'):=mmf(..vr) %>% {stringdist::stringdist(a=.[,1],b=.[,2],method='lcs')}] 
    }
    
    # dfy 
    crm2pwc[.(2),on='Y',dfy:=mmf('y',.SD) %>% apply(1,..Y)]
    # dfd 
    crm2pwc[.(2),on='D',dfd:=mmf('d',.SD) %>% apply(1,..D)]
    # dfv 
    crm2pwc[.(2),on='V',dfv:=mmf('v',.SD) %>% apply(1,..V)]
    # dfp 
    crm2pwc[.(2),on='P',dfp:=mmf('p',.SD) %>% apply(1,..P)]
    
    crm2pwc
  }
  pwc2mlm<-pwc2mlm.f()
  save(pwc2mlm,file=f)
}
rm(f)
```

```{r trn2sup}
f <- "d/qq/trn2sup.txt.gz"
if(file.exists(f)){
  trn2sup<-fread(f)
} else {
  # unlink(dir(pattern='trn2sup',recursive = T))
  # rm(smp)
  if(!'reg2trn'%in%ls()) load('d/q/reg2trn.RData')
  if(!'cg2sm'%in%ls()) load('d/p/cg2sm.RData')
  if(!'smp'%in%ls()) {load('d/q/crm2pwc.RData');smp<-crm2pwc[ec('hld,trn'),on='mls',unique(cmp) %>% sort %>% {.[seq(1,length(.),by=1)[1:100]]}
  ];rm(crm2pwc)}
  source('app.R')
  options(shiny.reactlog = F)
  options(shiny.reactlog = T)
  trn2sup.f(
    reg2trn,cg2sm,aspect=1,out = f,samp=smp,fntsz='auto'
    ,dcache = T,cache = sub('\\.txt\\.gz','-cache',f) %>% {if(dir.exists(.)) . else {dir.create(.);.}}
    ,brwsr=rstudioapi::viewer
  )
}
rm(f)
```

```{r sup2mlm}
f<-'d/q/sup2mlm.RData'
if(file.exists(f)){
  load(f)
} else {
  sup2mlm.f<-function(trnthr=500){
    trn2sup<-trn2sup[,.(fin=!all(group=='_')),by=cmp][(fin),cmp] %>%  {trn2sup[.(.),on='cmp']}
    sup<-trn2sup[,combn(label,2) %>% apply(2,sort) %>% t %>% data.table %>% setnames(ec('cr1,cr2')),by=cmp]
    sup[trn2sup,on='cr1==label',g1:=group]
    sup[trn2sup,on='cr2==label',g2:=group]
    sup[,match:=apply(.SD,1,function(x) all(x%in%LETTERS[1:6]))&(g1==g2),.SDcols=ec('g1,g2')]
    pwc2mlm[,ec('cr1,cr2'):=crp %>% pbapply::pblapply(X = .,FUN = sort,cl=3) %>% do.call(what=rbind) %>% data.table]
    pwc2mlm[sup,on=ec('cr1,cr2'),match:=match]
    pwc2mlm[.('prd',T),on=ec('mls,match'),mls:='trn']
    t<-pwc2mlm[,.(m=sum(match,na.rm = T)),by=.(par,mls)] %>% dcast(par~mls,value.var='m') %>% 
      {data.table(.[,.(par=par %>% as.character %>% c('Sum'))],.[,!'par'] %>% as.matrix %>% addmargins)} %>% na.omit
    via<-t[trn>trnthr,par]
    pwc2mlm[.(via),on='par'] %>% split(by='par') %>% 
      lapply(function(x) x[,.SD,.SDcols=which(sapply(x,function(y) y %>% is.na %>% mean %>% `==`(1) %>% `!`))])
  }
  sup2mlm<-sup2mlm.f()
  save(sup2mlm,file=f)
}
rm(f)
```

```{r mlm2mlc}
#' machine learning matrix 2 machine learning classifier
#' hpt hours per training
#' pmu proportion total memory to use
f<-'d/q/mlm2mlc.RData'
if(file.exists(f)){
  load(f)
} else {
  # hpt hours per table
  cat('\014')
  mlm2mlc.f<-function(hpt=4,pmu=3/4,shutdown=F){
    mlc<-list()
    prd<-list()
    withr::with_package('h2o',{
      h2o.init(
        nthreads=parallel::detectCores()-1
        ,max_mem_size = 
          system('sysctl hw.memsize',intern = T) %>% strsplit(' ') %>% {.[[1]][2]} %>% as.numeric %>% `*`(pmu) %>% {.-(.%%1024)}
      )
      for(i in names(sup2mlm)){
        fn<-paste0('h2o-',i)
        fnr<-paste0(fn,'-mlc')
        fnrf<-sub('mlc',fnr,f)
        if(file.exists(fnrf)) {mlc[[i]]$mod<-load(fnr);next}
        assign(fn,as.h2o(sup2mlm[[i]]['trn',on='mls',!ec('cmp,crp,Y,D,V,P,par,mls,cr1,cr2')][!is.na(match),][,match:=factor(match)]
          ,destination_frame = fn,use_datatable = TRUE))
        mlc[[i]]$mod<-h2o.automl(y='match',training_frame = get(fn),verbosity = 'info',max_runtime_secs = 60*60*hpt)
        assign(fnr,mlc[[i]]$mod)
        save(list=fnr,file=fnrf)
        h2o.save_mojo(object = mlc[[i]]$mod@leader,path = sub('\\.RData$','',f) %>% {if(!dir.exists(.)) {dir.create(.)};.} ,force = T)
        mlc[[i]]$prd<-data.table(sup2mlm[[i]],mlc[[i]]$mod@leader %>% {h2o.predict(.,sup2mlm[[i]][,as.h2o(.SD),.SDcols=.@model$names])} %>% as.data.table)
        mlc[[i]]$prd[,MaxPCC:=TRUE.>=PresenceAbsence::optimal.thresholds(na.omit(.SD)[,.(par,match,TRUE.)],opt.methods = 'MaxPCC',FPC=1,FNC=1)[,2]]
      }
      if(shutdown) h2o.shutdown(prompt=F) else warning('\nh2o cluster still active')
    })
    mlc
  }
  mlm2mlc<-mlm2mlc.f()
  save(mlm2mlc,file=f)
}
rm(f)
```

```{r mlc2fuz}
f<-'d/q/mlc2fuz.RData'
if(file.exists(f)){
  load(f)
} else {
  mlc2fuz.f<-function(){
    fuz<-lapply(names(mlm2mlc),function(x) mlm2mlc[[x]]$prd[(MaxPCC),.(zr=list(crp %>% unlist %>% unique %>% sort)),keyby=cmp])
    fuz<-rbindlist(fuz)[,.(zr=list(zr %>% unlist %>% unique %>% sort)),keyby=cmp]
    fuz
  }
  mlc2fuz<-mlc2fuz.f()
  save(mlc2fuz,file=f)
}
rm(f)
```

# Bimodal edge list

```{r dbl2bel}
f<-'d/p/dbl2bel.RData'
if(file.exists(f)){
  rm(wok2dbl)
  load(f)
} else {
  wok2dbl<-{if(DF) wok2dfl else wok2dbl}['CR',on='field'] # implement this inside dbl2bel
  wok2dbl[dbl2cro,on='val==cro',val:=cr]
  dbl2bel<-plagiat::dbl2bel.f(
    wok2dbl
    ,out=dirname(f),trim_doi = F,trim_anon = F,trim_loops = T,capitalize = F,trim_pendants = T
    ,saved_recode = if('mlc2fuz'%in%ls()) mlc2fuz$zr else NULL
  ) #%>% invisible
  save(dbl2bel,file=f)
  rm(wok2dbl)
}
r<-attributes(dbl2bel)$results
if('zcr'%in%names(dbl2bel)) dbl2bel %<>% {
  .[,cr:=NULL] %>% setnames('zcr','cr')
  .[,pend:=NULL] %>% setnames('zpend','pend')
  .[,loop:=NULL] %>% setnames('zloop','loop')
  .[!(zdup)]
}
dbl2bel<-unique(dbl2bel[!(pend|loop),.(ut,cr)]) %>% setkey(ut,cr)
dbl2bel[,`:=`(ut=factor(ut),cr=factor(cr))] %>% setkey(ut,cr)
of<-sprintf(paste(dirname(f),'bel2mel-%s-levs.txt',sep=.Platform$file.sep),ec('ut,cr')) %>% {names(.)<-ec('ut,cr');.}
for(i in names(of)) writeLines(dbl2bel[,levels(get(i))],of[i])
dbl2bel[,ut:=as.integer(ut)][,cr:=as.integer(cr)] %>% setkey(ut,cr)

if(DF) {
  dfl2bel<-as.disk.frame(dbl2bel,nchunks = nchnk,shardby = 'ut')
  attr(dfl2bel,'results')<-r
  rm(dbl2bel)
}
rm(f,r)
cpumem(plot=T)
```

# Unimodal edgelist

```{r dfbel2mel}
f<-'d/p/bel2mel.RData.txt'
if(file.exists(f)){
  warning(sprintf('%s already exists. Manually delete to replace.',f))
} else 
{
  #bel2mel<-plagiat::bel2mel.f(dbl2bel,type = 'crel',out = dirname(f))
  f %>% {if(file.exists(.)) {file.remove(.);warning(sprintf('Removed %s before writing new lines.',.))}}
  if(DF) {
    cat('\nStarting dfl2bel -> bel2mel.RData.txt.')
    dfl2bel[
      ,data.table(ut=ut,do.call(what='rbind',lapply(1:(length(cr) - 1), function(y) matrix(cr[c(rep(y,length(cr) - y), (y + 1):length(cr))], ncol = 2)))) %>% setnames(old=c('V1','V2'),new=c('cr1','cr2')) %>% 
        fwrite(file = f,append=T,quote = F,sep = '\t',nThread = 1)
      ,by = ut]
    cat(' Finished.')
    cat('\nStarting sort.')
    system.time(system(sprintf('time (head -n 1 %s && tail -n +2 %s | sort -k 2 -S 1G) > %s && rm %s',f,f,sub('\\.txt$','-sorted\\.txt',f),f)))
    cat(' Finished.')
  } else
  {
    bel2mel<-list()
    bel2mel$crel<-pbapply::pblapply(
      split(suppressWarnings(dbl2bel[,.(ut=ut %>% unique,batch=1:ceiling((ut %>% unique %>% length)/100))])[,.(ut,batch=sort(batch))],by = 'batch',keep.by = F)
      ,function(x) {
        r<-dbl2bel[x,data.table(do.call(rbind,lapply(1:(length(cr) - 1), function(y) matrix(cr[c(rep(y,length(cr) - y), (y + 1):length(cr))], ncol = 2)))),by = ut] %>% setnames(old=c('V1','V2'),new=c('cr1','cr2'))
        #if(DF) fwrite(x = r,file = f,append=T,quote = F,sep = '\t',nThread = 1) else
        r
      }
      ,cl=nc
    )
  }
  if(F){
    if(DF) {zip(zipfile = {z<-sub('$','.zip',f);z},files = f);file.remove(f)}
    dfbel2mel<-zip_to_disk.frame(zipfile = z,outdir = '.',nchunks=nchnk,shardby=ec('cr1,cr2'))[[1]]
  }
}
cpumem(T)
cat('\nStarting bel2mel.RData.txt -> dfbel2mel.')
dfbel2mel<-csv_to_disk.frame(
  infile=f %>% sub('RData','RData-sorted',.)
  #  ,outdir = '~/d/p/bel2mel.df' %>% path.expand %>% {dir.create(.);.}
  ,chunk_reader = 'data.table'
  ,nchunks=1
)
#pf2<-profvis::profvis({
try(rechunk(dfbel2mel,nchunks = 16,shardby=c('cr1','cr2'),overwrite=F,outdir = 'd/p/bel2mel.df'))
#    })
cat(' Finished.')
rm(f)
cpumem(plot=T)
```


```{r bel2mel-ew1.txt.gz}
f<-'d/p/bel2mel-ew1.txt.gz'
if(file.exists(f)){
  warning(sprintf('%s already exists. Manually delete to replace.',f))
} else 
{
  file.remove(f)
  file.remove(sub('1','2',f))
  cat('\nStarting dfbel2mel -> bel2mel-ew(1|2).txt.gz.')
  dfbel2mel[
    ,.SD[,.(ew =.N,ut=list(ut)),keyby=.(cr1,cr2)] %>% setkey(ew) %>% {
      .[.(1)] %>% fwrite(f,sep = '\t',sep2=c('"',',','"'),append=T)
      .[!.(1)] %>% fwrite(sub('1','2',f),sep = '\t',sep2=c('"',',','"'),append=T)
    }]
  cat(' Finished.')
}
# if(DF) {
#   dfbel2mel<-as.disk.frame(bel2mel$crel[,!'ut'])
#   attr(dfbel2mel,'results')<-attributes(bel2mel$crel)$results
#   #rm(dbl2bel)
# }
rm(f)
cpumem(plot=T)
```

```{r mel2g}
f<-'d/p/mel2g.RData'
if(file.exists(f)){
  load(f)
} else {
  mel2g.f<-function(){
    mel<-fread('d/p/bel2mel-ew2.txt.gz')
    g<-graph_from_edgelist(mel[,lapply(.SD, as.character),.SDcols=ec('cr1,cr2')] %>% as.matrix,directed = F)
    E(g)$weight<-mel[,ew]
    # read names from gz levels file, make a function
    ix<-data.table(ix=V(g)$name %>% as.integer)[,o:=.I] %>% setkey(ix)
    ix[,skp:=c(ix[1],diff(ix))-1]
    #con <- gzfile(description = "d/p/bel2mel-cr-levs.txt.gz",open = 'r') #create file connection
    con <- file(description = "d/p/bel2mel-cr-levs.txt",open = 'r') #create file connection
    ix[,n:=pbapply::pbsapply(skp, function(i) scan(file = con,what=character(),skip=i,nlines=1,sep='\n',quiet = T),cl=1)]
    close(con)
    ix %>% setorder(o)
    V(g)$ix<-as.integer(V(g)$name)
    V(g)$name<-ix$n %>% unlist
    gd<-degree(g) %>% table %>% sort(T)
    cat('head and tail of degrees\n')
    print(head(gd))
    print(tail(gd))
    set_graph_attr(g,'mew',mel[,max(ew)])
  }
  mel2g<-mel2g.f()
  save(mel2g,file=f)
}
rm(f)
```

```{r g2dd, paged.print=FALSE}
f<-'d/q/g2dd.RData'
if(file.exists(f)){
  load(f)
} else {
  g2dd.f<-function(rnd=4){
    dd<-data.table(dd=mel2g %>% degree)[,.N,by=dd] %>% setkey(dd)
    dd[,pN:=prop.table(N)*100][,Ncum:=cumsum(N)][,pNcum:=cumsum(pN)]
    ed<-data.table(ed=E(mel2g)$weight)[,.N,by=ed] %>% setkey(ed)
    ed[,pN:=prop.table(N)*100][,Ncum:=cumsum(N)][,pNcum:=cumsum(pN)]
    list(dd=dd,ed=ed)  %>% lapply(function(x) x[,.SD %>% lapply(round,rnd)])
  }
  g2dd<-g2dd.f()
  save(g2dd,file=f)
  mapply(x=g2dd,n=names(g2dd),function(x,n) fwrite(
    x,quote = F,sep='\t'
    ,file=sub('dd.RData',paste0(n,'.txt'),f,fixed = T)
  )) %>% invisible
}
rm(f)
# degree and edge weight distributions
g2dd
```

```{r g2cg}
f<-'d/p/g2cg.RData'
if(file.exists(f)){
  load(f)
} else {
  g2cg<-cluster_louvain(mel2g)
  g2cg$ix<-V(mel2g)$ix
  save(g2cg,file=f)
}
V(mel2g)$h1<-membership(g2cg)
rm(f)
```

```{r cg2sm}
# community graph to sequenced membership
f<-'d/p/cg2sm.RData'
if(file.exists(f)){
  load(f)
} else {
  cg2sm.f<-function(){
    # rename cluster ids to be in sequence by size
    sm<-g2cg %>% {data.table(.$names,.$memberships %>% t)} %>% {setnames(.,c('id',paste0('h',if(ncol(.)-1) {(ncol(.)-1):1} else 1)))}
    cm<-names(sm) %>% setdiff('id')
    om<-sub('h','o',cm)
    sm[,(om):=.SD %>% lapply(as.integer),.SDcols=cm]
    sm[,(cm):=.SD %>% lapply(function(x) x %>% factor %>% forcats::fct_infreq(.) %>% as.integer),.SDcols=cm]
    sm[,str:=strength(graph = mel2g,loops = F)] # TODO figure out how to separate within and between community ties, count directly in 2mel
    sm[,deg:=degree(graph = mel2g,loops = F)] 
    sm[,mut:=str/deg] # mean number of publications 
    sm
  }
  cg2sm<-cg2sm.f()
  save(cg2sm,file=f)
}
rm(f)
smd<-cg2sm[,.N,by=h1] %>% setorder(-N) %>% .[,P:=N %>% prop.table %>% `*`(100) %>% round(3)]
smt<-smd[,.(n=.N),by=N][,P:=n %>% prop.table %>% `*`(100) %>% round(3)] %>% setorder(N)
smt[,cn:=cumsum(n)][,cP:=cumsum(P)]
smt %>% fwrite('d/q/smt.txt') # sequenced membership table
smt %>% knitr::kable(.)
```



```{r sm2samp}
f<-'d/q/sm2samp'
if(dir.exists(f)){
  warning('Existing d/q/sm2samp will *not* be overwritten. Manually delete to replace.')
} else {
  MBR <- function(p) { #https://gis.stackexchange.com/a/22934
    # Analyze the convex hull edges     
    a <- chull(p)                                   # Indexes of extremal points
    a <- c(a, a[1])                                 # Close the loop
    e <- p[a[-1],] - p[a[-length(a)], ]             # Edge directions
    norms <- sqrt(rowSums(e^2))                     # Edge lengths
    v <- e / norms                                  # Unit edge directions
    w <- cbind(-v[,2], v[,1])                       # Normal directions to the edges
    
    # Find the MBR
    vertices <- p[a, ]                              # Convex hull vertices
    x <- apply(vertices %*% t(v), 2, range)         # Extremes along edges
    y <- apply(vertices %*% t(w), 2, range)         # Extremes normal to edges
    areas <- (y[1,]-y[2,])*(x[1,]-x[2,])            # Areas
    k <- which.min(areas)                           # Index of the best edge (smallest area)
    
    # Form a rectangle from the extremes of the best edge
    cbind(x[c(1,2,2,1,1),k], y[c(1,1,2,2,1),k]) %*% rbind(v[k,], w[k,])
  }
  pMBR<-function(mbr,p){
    limits <- apply(mbr, 2, range) # Plotting limits
    plot(p[(function(x) c(x, x[1]))(chull(p)), ], 
      type="l", asp=1, bty="n", xaxt="n", yaxt="n",
      col="Gray", pch=20, 
      xlab="", ylab="",
      xlim=limits[,1], ylim=limits[,2])                # The hull
    lines(mbr, col="Blue", lwd=3)                         # The MBR
    points(p, pch=19)                                     # The points
  }
  mug<-function(g,f,s){ # function and slug, merge selected attributes of graph union
    n<-list(V=igraph::vertex_attr_names(g),E=igraph::edge_attr_names(g))
    n<-grep(s,n[[f]],value=T)
    m<-do.call(cbind,lapply(n,function(x) eval(parse(text=sprintf('%s(g)$%s',f,x)))))
    apply(m,1,function(x) x %>% na.omit %>% unique)
  }
  sm2samp.f<-function(lim=20,ego=1,iterations=1000,seed=12345,plot=T,fr=ec('igraph,network')){
    set.seed(seed)
    dir.create(f)
    samp<-smd[between(N,2,lim),.(h1=if(.N<=10) h1 else sample(h1,10) %>% sort),by=N]
    r<-merge(cg2sm[,.(h1,id,str,deg,mut=round(mut,1))],samp,by='h1') %>% setorder(N,h1,-str,-mut)
    nf<-max(nchar(r$h1))
    withr::with_package('showtext',{
      font_add_google('Wire One','Wire One')
      showtext_auto()
      rg<-r[, list({
        d<-paste(f,sprintf(N[1],fmt=paste0('N%0',nchar(lim),'d')),sep = .Platform$file.sep)
        if(!dir.exists(d)) dir.create(d)
        p<-paste(d,sprintf(h1[1],fmt=paste0('C%0',nf,'d.txt')),sep=.Platform$file.sep)
        options(datatable.print.nrows=.N)
        tp<-capture.output(print(.SD[,.(str,deg,mut,id)]))
        writeLines(tp[-length(tp)],con=p)
        g<-do.call(igraph::union,make_ego_graph(graph = mel2g,order=ego,nodes=id))
        sg<-strength(g)
        sgi<-sg %>% {.-min(.)+1}
        vpal<-viridis::viridis(max(sgi),option = 'viridis')
        ew<-mug(g,'E','weight')
        ewi<-ew %>% {.-min(.)+1}
        epal<-viridis::viridis(max(ewi),option = 'magma',direction=-1)
        withr::with_seed(seed,{
          if(fr[1]=='igraph') {
            lyt<-igraph::layout_with_fr(g,niter=iterations,weights=ew)
          } else{
            net<-intergraph::asNetwork(g)
            lyt<-network::network.layout.fruchtermanreingold(net,layout.par = NULL)
          }
          #
          
        })
        if(plot) {
          pdf(sub('txt$','pdf',p))
          par(bg='gray')
          plot.igraph(
            g
            ,layout=lyt
            ,edge.color=epal[ewi]
            ,vertex.color=vpal[sgi]  %>%  {.[!(mug(g,'V','name')%in%id)]<-'gray';.}
            ,vertex.frame.color=ec('white,black')[(mug(g,'V','name')%in%id)+1]
            ,vertex.label.color=ec('darkgray,black')[(mug(g,'V','name')%in%id)+1]
            ,vertex.label.family='Wire One'
            ,vertex.size=5
            ,vertex.label.cex=.75
            ,main=paste('N:',N[1],'C:',h1[1])
            ,sub='top bar: node strength (sum of edge weights) \nbottom bar: number of citing articles (edge weight)'
          )
          plotrix::color.legend(-1,1.1,1,1.15,legend=range(sg) %>% {.[1]:.[2]} %>% {.[!.%in%sg]<-'';.},rect.col = vpal,align = 'lt',gradient='x',cex = .5,col='white',font=2)
          plotrix::color.legend(-1,-1.15,1,-1.1,legend=range(ew) %>% {.[1]:.[2]} %>% {.[!.%in%ew]<-'';.},rect.col = epal,align = 'rb',gradient='x',cex = .5,col='white',font=2)
          dev.off()
        }
        cat('.')
        list(set_graph_attr(g,'layout',lyt))
      }),by=.(N,h1)]$V1
    })
    cat('\n')
    warning(sprintf('\ncluster samples printed to %s',f))
    rg
  }
  system.time(sm2samp<-sm2samp.f(plot=T))
}
rm(f)
#1 %>% {withr::with_seed(seed,plot(intergraph::asNetwork(rev(sm2samp)[[.]])))} %>% {pMBR(MBR(.),.)}
```

```{r sm2cc}
# Johann has to decide size cutoff for communities
Ncut<-6
sm2cc<-cg2sm[.(smd[N>=Ncut]$h1),on='h1'] %>% setorder(h1,-str)
```


```{r cc2lab}
f<-'d/q/cc2lab.txt'
if(file.exists(f)){
  load(f)
} else {
  cc2lab.f<-function(){
    cc2lab<-sm2cc[,.SD %>% head(10),by=h1,.SDcols=ec('id,str,deg,mut')] %>% data.table(code='',.)
    fwrite(copy(cc2lab)[,mut:=round(mut,1)],file=f,quote=F,sep='\t')
    
    DT::datatable(.,editable=list(target='cell',disable=list(columns=c(0,2:4)))) 
    
    #%>% htmlwidgets::saveWidget(.,file=sprintf('%s/d/b/clusterbrowser.html',getwd()),selfcontained = T)
    # TODO make a shiny app that has an editable table that will save a csv with fwrite
    
  }
  cc2lab<-cc2lab.f()
  save(cc2lab,file=f)
}
rm(f)
```


```{r cc2yr}
# TODO make sure <NA> in merge aren't errors
f<-'d/p/cc2yr.RData'
if(file.exists(f)){
  load(f)
} else {
  cc2yr.f<-function(){
    # wkd<-function() {if(DF) wok2dfl else wok2dbl}
    # if(!DF) 
    load('d/p/wok2dbl.RData')
    if(!'ogcr'%in%ls()) load('d/p/dbl2bel-ogcr.RData')
    ut<-CJ(id=wok2dbl[CJ(field='CR',val=sm2cc$id),on=ec('field,val'),id] %>% unique,field='PY') %>% na.omit
    og<-CJ(field='CR',val=ogcr[sm2cc$id,on='t',og]) %>% na.omit
    yr<-merge(
      wok2dbl[og,on=ec('field,val'),.(id,cr=val)] %>% na.omit %>% unique
      ,wok2dbl[ut,on=ec('id,field'),.(id,yr=as.integer(val))] %>% na.omit %>% unique
      ,by='id',allow.cartesian=TRUE)
    setnames(yr,'cr','og')
    yr[ogcr,on='og',cr:=t]
    rm(wok2dbl)
    rm(ogcr)
    yr<-merge(yr,sm2cc[,.(id,h1)],by.x='cr',by.y='id')[,.N,keyby=.(h1,yr)]
    yr
  }
  cc2yr<-cc2yr.f()
  save(cc2yr,file=f)
}
rm(f)
p<-cc2yr[,.(N=sum(N)),by=yr][,ggplot(data=.SD,aes(x=yr,y=N))+geom_line()+geom_point(color='white',size=.5)+geom_rug()]
cowplot::plot_grid(p,p+scale_y_log10(),ncol=1)

ctg<-cc2yr %>% setorder(h1,yr) %>% {.[,.(ctg=.N/{(yr %>% range %>% diff)-.N+1}),by=h1]} %>% {.[,c1:=factor(h1,levels=h1[order(ctg,decreasing = T)]) %>% as.integer]}
cc2yr[ctg,on='h1',c1:=c1]


hm<-list();for(v in c(T,F)){
  h<-{ggplot(
    copy(cc2yr)[,h1:=if(v) h1 else c1][,`:=`(id=as.character(h1),h1=factor(h1) %>% as.integer,cut=cut(N,breaks=c(0,1,10,max(N))))]
    ,color='white',size=.1,aes(y=h1,x=yr)) + theme_gray() + 
      coord_fixed() + 
      scale_x_continuous(expand = c(0,0),breaks = seq(1920,2020,20),minor_breaks = seq(1910,2010,20),limits = c(NA,2020),sec.axis = dup_axis()) + 
      scale_y_continuous(expand = c(0,0),breaks=NULL) + 
      theme(axis.text.y = element_blank(),legend.position = 'none',plot.background = element_rect(fill='gray92'),panel.background = element_rect(fill=NA),panel.ontop = v,panel.grid.major = element_line(size = rel(0.5)),title = element_text(size=8)) + xlab(NULL)+ylab('')}
  cowplot::plot_grid(
    h+geom_tile(aes(fill=N))+ scale_fill_viridis_c(option='plasma') + ggtitle('N citations by cluster') + ylab(ifelse(v,'<-- larger total cluster size','<-- more contiguous cluster spread'))
    ,h+geom_tile(aes(fill=log(N)))+ scale_fill_viridis_c(option='plasma') + ggtitle('log(N) citations and cluster')
    ,h+geom_tile(aes(fill=cut)) + ggtitle('Red:N=1, Green:1<N<11, Blue:N>10')
    ,h+geom_tile(aes(fill=cut %>% forcats::fct_rev(.) %>% {levels(.) %<>% replace(.,2:3,NA);.})) + scale_fill_hue(h=c(360/3*2,360)+15,na.value='gray92') + ggtitle('N>10 (Blue only) ')
    ,nrow = 1)->hm[[length(hm)+1]]
}
144 %>% {ggsave('d/b/heat-sort-size.pdf',plot=hm[[1]],units = 'in',dpi = .,width = 1920/.,height=1080/.)}
144 %>% {ggsave('d/b/heat-sort-contiguity.pdf',plot=hm[[2]],units = 'in',dpi = .,width = 1920/.,height=1080/.)}
```

```{r yr2cp}
f<-'d/p/yr2cp.RData' #%>% unlink
if(file.exists(f)){
  load(f)
  load(sub('yr2cp','cp2all',f))
} else {
  yr2cp.f<-function(cc2yr){
    ryr<-cc2yr$yr %>% range %>% as.list %>% do.call(what=seq)
    grd<-dcast(
      copy(cc2yr)[,yr:=factor(yr,levels = ryr)]
      ,formula=yr~h1,value.var = 'N',fill=0,drop = F) %>% 
      setorder(yr)
    withr::with_seed(12345,{
      t<-lapply(1:3,function(x) data.table(ov2chpt.f(grd[,!'yr'],drv = x,drv.only = T)) %>% {.[,.SD,.SDcols=-(1:(ncol(.)/2))]}) %>% do.call(what=data.table) %>% {data.table(grd,.)}
    })
    cmb<-data.table(n=names(t)[-1])[,key:=strsplit(n,'_') %>% sapply(last)][!grepl('d',key),key:='d0']
    set<-cmb$key %>% unique %>% {lapply(1:length(.),function(x) combn(.,x) %>% data.table)} %>% do.call(what=c)
    ncmb<-sapply(set,paste0,collapse='_')
    names(set)<-ncmb
    set<-lapply(set,function(x) cmb[x,on='key',n])
    per<-pbapply::pblapply(set,function(sd) ecp::e.divisive(t[,.SD,.SDcols=sd],min.size=2,sig.lvl = .01,R=1000),cl=nc)
    grp<-data.table(yr=grd$yr,sapply(per,function(x) x$cluster))
    all<-melt(grp,id.vars = 'yr',variable.name='cmb',value.name='period')
    all[,cmb:=factor(cmb,levels=ncmb)][,period:=factor(period)]
    ap<-ggplot(copy(all)[,yr:=yr %>% as.character %>% as.integer]) + stat_bin(geom='area',position='identity',aes(x=yr,fill=period),binwidth = 1,alpha=.75,color=NA)+scale_fill_brewer(palette=ifelse(uniqueN(all$period)>8,'Paired','Dark2')) + scale_x_continuous(expand=c(0,0))+ scale_y_continuous(expand=c(0,0))
    list(dat=all,plt=ap)
  }
  cp2all.f<-function(cc2yr){
    ryr<-cc2yr$yr %>% range %>% as.list %>% do.call(what=seq)
    grd<-dcast(
      copy(cc2yr)[,yr:=factor(yr,levels = ryr)]
      ,formula=yr~h1,value.var = 'N',fill=0,drop = F) %>% 
      setorder(yr)
    withr::with_seed(12345,{
      grd<-grd[,.(yr,a=.SD %>% apply(1,sum)),.SDcols=!'yr']
      a<-lapply(1:3,function(x) data.table(ov2chpt.f(grd[,!'yr'],drv = x,drv.only = T)) %>% {.[,.SD,.SDcols=-(1:(ncol(.)/2))]}) %>% do.call(what=data.table) %>% {data.table(grd,.)}
    })
    cmb<-names(a)[-1] %>% {lapply(1:length(.),function(x) combn(.,x) %>% data.table)} %>% do.call(what=c)
    ncmb<-sapply(cmb,function(x) sub('a_','',x) %>% paste0(collapse='_'))
    names(cmb)<-ncmb
    per<-pbapply::pblapply(cmb,function(sd) ecp::e.divisive(a[,.SD,.SDcols=sd],min.size=2,sig.lvl = .01,R=1000),cl=nc)
    grd<-data.table(grd,sapply(per,function(x) x$cluster) %>% data.table)
    all<-melt(grd,id.vars = ec('yr,a'),variable.name='cmb',value.name='period')
    all[,cmb:=factor(cmb,levels=ncmb)][,period:=factor(period)]
    all %>% setnames('a','A')
    ap<-ggplot(copy(all)[,yr:=yr %>% as.character %>% as.integer]) + stat_bin(geom='area',position='identity',aes(x=yr,fill=period),binwidth = 1,alpha=.75,color=NA)+scale_fill_brewer(palette=ifelse(uniqueN(all$period)>8,'Paired','Dark2')) + scale_x_continuous(expand=c(0,0))+ scale_y_continuous(expand=c(0,0))
    list(dat=all,plt=ap)
  }
  
  #linear growth assumption
  yr2cp<-yr2cp.f(cc2yr)
  save(yr2cp,file=f)
  fwrite(yr2cp$dat %>% dcast(yr~cmb,value.var='period'),file=sub('p','b',f) %>% sub('RData','csv',.),sep=',',quote = F)
  144 %>% {ggsave(sub('p','b',f) %>% sub('RData','png',.),plot=yr2cp$plt,units = 'in',dpi = .,width = 1920/.,height=1080/.)}
  htmlwidgets::saveWidget(file = sub('p','b',f) %>% sub('RData','html',.) %>% paste(getwd(),.,sep='/'),widget =  yr2cp$plt %>% plt(hovinf = 'text'))
  
  cp2all<-cp2all.f(cc2yr)
  save(cp2all,file=sub('yr2cp','cp2all',f))
  fwrite(cp2all$dat %>% dcast(yr+A~cmb,value.var='period'),file=sub('p','b',sub('yr2cp','cp2all',f)) %>% sub('RData','csv',.),sep=',',quote = F)
  144 %>% {ggsave(sub('p','b',sub('yr2cp','cp2all',f)) %>% sub('RData','png',.),plot=cp2all$plt,units = 'in',dpi = .,width = 1920/.,height=1080/.)}
  htmlwidgets::saveWidget(file = sub('p','b',sub('yr2cp','cp2all',f)) %>% sub('RData','html',.) %>% paste(getwd(),.,sep='/'),widget =  cp2all$plt %>% plt(hovinf = 'text'))
  
  # "logarithmic" (Inverse hyperbolic sine) growth assumption
  yr2cp_ihs<-yr2cp.f(copy(cc2yr)[,N:=ihs(N)])
  save(yr2cp_ihs,file=sub('\\.RData','-ihs.csv',f))
  fwrite(yr2cp_ihs$dat %>% dcast(yr~cmb,value.var='period'),file=sub('p','b',f) %>% sub('\\.RData','-ihs.csv',.),sep=',',quote = F)
  144 %>% {ggsave(filename = sub('p','b',f) %>% sub('\\.RData','-ihs.png',.),plot=yr2cp_ihs$plt,units = 'in',dpi = .,width = 1920/.,height=1080/.)}
  htmlwidgets::saveWidget(file = sub('p','b',f) %>% sub('\\.RData','-ihs.html',.) %>% paste(getwd(),.,sep='/'),widget =  yr2cp_ihs$plt %>% plt(hovinf = 'text'))
  
  cp2all_ihs<-cp2all.f(copy(cc2yr)[,N:=ihs(N)])
  save(cp2all_ihs,file=sub('yr2cp','cp2all-ihs',f))
  fwrite(cp2all_ihs$dat %>% dcast(yr+A~cmb,value.var='period'),file=sub('p','b',sub('yr2cp','cp2all',f)) %>% sub('\\.RData','-ihs.csv',.),sep=',',quote = F)
  144 %>% {ggsave(filename = sub('p','b',sub('yr2cp','cp2all',f)) %>% sub('\\.RData','-ihs.png',.),plot=cp2all_ihs$plt,units = 'in',dpi = .,width = 1920/.,height=1080/.)}
  htmlwidgets::saveWidget(file = sub('p','b',sub('yr2cp','cp2all',f)) %>% sub('\\.RData','-ihs.html',.) %>% paste(getwd(),.,sep='/'),widget =  cp2all_ihs$plt %>% plt(hovinf = 'text'))
  
}
rm(f)
```

```{r mel2cel}
# community edge lists
f<-'d/p/mel2cel.RData'
if(file.exists(f)){
  load(f)
} else {
  mel2cel.f<-function(){
    mel<-fread('d/p/bel2mel-ew2.txt.gz')
  }
  mel2cel<-mel2cel.f()
  save(mel2cel,file=f)
}
rm(f)
```
